### ISSUE TITLE
Unexpected Error when deleting calendar event

### ISSUE THREAD

**Issue by cb-octavian** [Cloudbakers/agm#12]
Unexpected error when running calendar delete command `agm calendar events delete --calendarId [calendarId] --eventId [eventId] --user [User]`

Error returned: 

`Unexpected error, please report to https://github.com/Cloudbakers/agm/issues
Traceback (most recent call last):
  File "/home/octavian/.local/bin/agm", line 11, in <module>
    sys.exit(cli())
  File "/home/octavian/.local/lib/python3.6/site-packages/agm/agm.py", line 177, in cli
    raise e
  File "/home/octavian/.local/lib/python3.6/site-packages/agm/agm.py", line 165, in cli
    run(fully_parsed_args)
  File "/home/octavian/.local/lib/python3.6/site-packages/agm/agm.py", line 238, in run
    executor.multithread_execute_requests(requests, scopes=scopes)
  File "/home/octavian/.local/lib/python3.6/site-packages/agm/executor.py", line 140, in multithread_execute_requests
    chunk_responses += [future.result()]  # Doesnt actually return anything
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/octavian/.local/lib/python3.6/site-packages/agm/executor.py", line 181, in execute_requests
    Batch(service, requests_chunk).execute()
  File "/home/octavian/.local/lib/python3.6/site-packages/agm/executor.py", line 263, in execute
    return batch.execute()
  File "/home/octavian/.local/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/octavian/.local/lib/python3.6/site-packages/googleapiclient/http.py", line 1490, in execute
    self._callback(request_id, response, exception)
  File "/home/octavian/.local/lib/python3.6/site-packages/agm/executor.py", line 285, in batch_callback
    request.callback(response)
  File "/home/octavian/.local/lib/python3.6/site-packages/agm/executor.py", line 113, in json_callback
    if not output.get("response", {}).get("nextPageToken"):
AttributeError: 'str' object has no attribute 'get'`

Event is still deleted successfully

**Comment by alexwennerberg** [comment]
Thanks for reporting this! Fixed in 9168e15
