### ISSUE TITLE
Listing users unexpected error

### ISSUE THREAD

**Issue by CB-korey** [Cloudbakers/agm#6]
When running command: **agm directory users list**
Error: Traceback (most recent call last):
  File "/home/ktibbs/.local/bin/agm", line 11, in <module>
    sys.exit(cli())
  File "/home/ktibbs/.local/lib/python3.6/site-packages/agm/agm.py", line 177, in cli
    raise e
  File "/home/ktibbs/.local/lib/python3.6/site-packages/agm/agm.py", line 165, in cli
    run(fully_parsed_args)
  File "/home/ktibbs/.local/lib/python3.6/site-packages/agm/agm.py", line 230, in run
    requests = get_list_of_requests(fully_parsed_args)
  File "/home/ktibbs/.local/lib/python3.6/site-packages/agm/agm.py", line 252, in get_list_of_requests
    version = request_cmd.get("version") or docs.get_preferred_version(service)
  File "/home/ktibbs/.local/lib/python3.6/site-packages/agm/docs.py", line 61, in get_preferred_version
    return versions[0]
IndexError: list index out of range

Have verified that the following API is enabled to utilize this command: https://www.googleapis.com/auth/admin.directory.user

**Comment by alexwennerberg** [comment]
It looks like the Admin SDKs, which are a special case, are broken at the moment. Will fix for 0.1.4

**Comment by alexwennerberg** [comment]
Fixed in f2477fa55d519a1f6a1d4b2a7a8845de3006b431
