### ISSUE TITLE
Get directory user Error

### ISSUE THREAD

**Issue by CB-korey** [Cloudbakers/agm#8]
While running the following: agm directory users get cloudbakers@levelup-mail.com
With These APIs in scope: https://www.googleapis.com/auth/admin.directory.user
https://www.googleapis.com/auth/admin.directory.user.readonly

I receive this error: Traceback (most recent call last):
  File "/home/ktibbs/.local/bin/agm", line 11, in <module>
    sys.exit(cli())
  File "/home/ktibbs/.local/lib/python3.6/site-packages/agm/agm.py", line 177, in cli
    raise e
  File "/home/ktibbs/.local/lib/python3.6/site-packages/agm/agm.py", line 165, in cli
    run(fully_parsed_args)
  File "/home/ktibbs/.local/lib/python3.6/site-packages/agm/agm.py", line 228, in run
    list(map(docs.parse_scopes, args.get("scopes") or [])) or method.get_scopes()
  File "/home/ktibbs/.local/lib/python3.6/site-packages/agm/docs.py", line 212, in get_scopes
    return self.docs.get("scopes")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by alexwennerberg** [comment]
The issue is that the first three arguments are positional arguments. You'll need to set an admin user (--user [email]) and then the user you want information about (--userKey [target email]). See https://developers.google.com/admin-sdk/directory/v1/reference/users/get.

I will improve the error message for the next build

**Comment by alexwennerberg** [comment]
Improved error handling in 3d8f81a
